### ISSUE TITLE
Native rails caching

### ISSUE THREAD

**Issue by kaspergrubbe** [dogweather/asset_ram#1]
> My site's footer is static except for the asset links to e.g. social media icons. AFAIK, I can't use Rails caching for the entire footer because the asset fingerprints could change on the next reboot. I don't believe the Rails cache API has an option for that expiration type.

An approach you could use for native rails caching is to include something like the following into the cache-key:

- when server was started
- when the deploy happened
- the commit-hash
- the version number (if available)

**Comment by dogweather** [comment]
Those are good ideas. I'd also want to configure a second Rails cache, a memory store. And then I'd want to configure it (if possible) to not impose a limit of the RAM it can use.

I'm not sure if that extra setup outweighs using this gem.
