### ISSUE TITLE
Rails 7 performance

### ISSUE THREAD

**Issue by kirantpatil** [dogweather/asset_ram#2]
Hi,

Have you done Rails 7 performance check.

Since it supports HTTP2 and assets are not bundled. 

Regards,
Kiran.

**Comment by dogweather** [comment]
That's an interesting question. I'm still on Rails 6 and haven't tried upgrading it yet. I'll comment here when I do.

**Comment by dogweather** [comment]
I'm on Rails 7 now — I'll do a comparison.

**Comment by dogweather** [comment]
Yep, I'm getting a 17.6% improvement in allocations on [my app's homepage](https://www.public.law/). I'll post a writeup.
